language: java
jdk:
  - oraclejdk8
  - openjdk8

env:
  global:
    - "GALAXY_APIKEY=admin"
    - "GALAXY_URL=http://localhost/"
  matrix:
    - "GALAXY_VERSION=19.05.1"
    - "GALAXY_VERSION=19.01"
    - "GALAXY_VERSION=18.09"
    - "GALAXY_VERSION=18.05"
    - "GALAXY_VERSION=18.01"
    - "GALAXY_VERSION=17.09"
    - "GALAXY_VERSION=17.05"
    - "GALAXY_VERSION=17.01"
services:
  - docker  
before_install:
  - docker pull bgruening/galaxy-stable:$GALAXY_VERSION
  - docker run -d -p 80:80 -e GALAXY_CONFIG_MASTER_API_KEY=$GALAXY_APIKEY bgruening/galaxy-stable:$GALAXY_VERSION
  - docker ps
  - sleep 180
install:
  - mvn -version
  - mvn clean package install -DskipTests -Dgpg.skip
after_failure:
 - echo "Tests failed, dumping all logs."
 - cat /tmp/**/bootstrap-log/*
script: travis_wait mvn test -B
